allowBuilds:
  "@sentry/cli": true
  dtrace-provider: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@expo/cli@57.0.13"
  - "@expo/config-plugins@57.0.7"
  - babel-preset-expo@57.0.6
  - expo-asset@57.0.9
  - expo-file-system@57.0.2
  - expo-modules-core@57.0.10
  - expo@57.0.11
  - expo-background-task@57.0.8
  - expo-build-properties@57.0.9
  - expo-image-manipulator@57.0.8
  - expo-image-picker@57.0.8
  - expo-location@57.0.8
  - expo-notifications@57.0.9
  - expo-router@57.0.11
  - expo-symbols@57.0.2
  - expo-task-manager@57.0.8
patchedDependencies:
  expo-modules-jsi@57.0.4: patches/expo-modules-jsi@57.0.4.patch
  react-native-google-mobile-ads@16.3.4: patches/react-native-google-mobile-ads@16.3.4.patch
  react-native-webview@13.16.1: patches/react-native-webview@13.16.1.patch
