import type { CatalogLanguage } from "@/localization/catalogs";

const en = {
  settingsEntry: "Updates & diagnostics",
  screenTitle: "Update diagnostics",
  sectionUpdate: "Over-the-air updates",
  environmentChannel: "Environment / channel",
  runtime: "Runtime",
  updateId: "Update ID",
  currentSource: "Current source",
  lastCheck: "Last update check",
  neverChecked: "Not checked yet",
  lastResultNoUpdate: "Latest",
  lastResultDownloaded: "Downloaded",
  lastResultError: "Failed",
  embeddedSource: "Embedded app version",
  otaSource: "EAS OTA update",
  check: "Check and download update",
  checking: "Checking…",
  restartDownloaded: "Restart and apply downloaded update",
  statusDisabled: "OTA updates are disabled in development.",
  statusThrottled: "An update check just completed.",
  statusNoUpdate: "You already have the latest version.",
  statusDownloaded: "The update is downloaded. Restart now or apply it on the next cold launch.",
  statusError: "Update check failed. You can keep using the current stable version.",
  applyTitle: "Apply new version",
  applyMessage: "The app will restart immediately.",
  applyNow: "Restart now",
  operationFailed: "The operation failed. The current stable version is still available.",
  sectionRemote: "Remote configuration and emergency switches",
  configSource: "Configuration source",
  configVersion: "Configuration version",
  maintenanceMode: "Maintenance mode",
  paymentFeature: "Payment feature",
  enabled: "On",
  disabled: "Off",
  refreshConfig: "Refresh remote configuration",
  refreshingConfig: "Refreshing…",
  remoteRefreshFailed: "Refresh failed; cached or built-in defaults remain active.",
  sectionNative: "Installed native capability checks",
  notificationPermission: "Notification permission",
  photoPicker: "Photo library picker",
  currentLocation: "Current location",
  allowed: "Allowed",
  notAllowed: "Not allowed",
  selectedFiles: "Selected {count} file(s)",
  nativeCheckFailed: "The native capability check failed.",
  sectionDiagnostics: "Diagnostics",
  app: "App",
  api: "API",
  copyDiagnostics: "Copy diagnostics without sensitive data",
  copiedTitle: "Copied",
  copiedMessage: "Update diagnostics were copied without account data or tokens.",
} as const;

export type UpdateCopyKey = keyof typeof en;
type UpdateCopy = Record<UpdateCopyKey, string>;

const copies: Record<CatalogLanguage, UpdateCopy> = {
  en,
  ja: {
    settingsEntry: "アップデートと診断",
    screenTitle: "アップデート診断",
    sectionUpdate: "OTAアップデート",
    environmentChannel: "環境 / チャンネル",
    runtime: "ランタイム",
    updateId: "アップデートID",
    currentSource: "現在の提供元",
    lastCheck: "最終アップデート確認",
    neverChecked: "未確認",
    lastResultNoUpdate: "最新版",
    lastResultDownloaded: "ダウンロード済み",
    lastResultError: "失敗",
    embeddedSource: "アプリ内蔵版",
    otaSource: "EAS OTAアップデート",
    check: "アップデートを確認してダウンロード",
    checking: "確認中…",
    restartDownloaded: "再起動してダウンロード済み更新を適用",
    statusDisabled: "開発環境ではOTAアップデートを確認しません。",
    statusThrottled: "直前にアップデートを確認しました。",
    statusNoUpdate: "現在のバージョンが最新です。",
    statusDownloaded: "アップデートをダウンロードしました。今すぐ再起動するか、次回のコールド起動時に適用できます。",
    statusError: "アップデートの確認に失敗しました。現在の安定版は引き続き利用できます。",
    applyTitle: "新しいバージョンを適用",
    applyMessage: "アプリはすぐに再起動します。",
    applyNow: "今すぐ再起動",
    operationFailed: "操作に失敗しました。現在の安定版は引き続き利用できます。",
    sectionRemote: "リモート設定と緊急スイッチ",
    configSource: "設定の取得元",
    configVersion: "設定バージョン",
    maintenanceMode: "メンテナンスモード",
    paymentFeature: "支払い機能",
    enabled: "オン",
    disabled: "オフ",
    refreshConfig: "リモート設定を更新",
    refreshingConfig: "更新中…",
    remoteRefreshFailed: "更新に失敗しました。キャッシュまたは内蔵の既定値を使用しています。",
    sectionNative: "組み込み済みネイティブ機能の確認",
    notificationPermission: "通知権限",
    photoPicker: "写真ライブラリ選択",
    currentLocation: "現在地",
    allowed: "許可済み",
    notAllowed: "未許可",
    selectedFiles: "{count}件のファイルを選択しました",
    nativeCheckFailed: "ネイティブ機能の確認に失敗しました。",
    sectionDiagnostics: "診断",
    app: "アプリ",
    api: "API",
    copyDiagnostics: "機密情報を含まない診断情報をコピー",
    copiedTitle: "コピーしました",
    copiedMessage: "アカウント情報やトークンを含まない更新診断をコピーしました。",
  },
  ko: {
    settingsEntry: "업데이트 및 진단",
    screenTitle: "업데이트 진단",
    sectionUpdate: "OTA 업데이트",
    environmentChannel: "환경 / 채널",
    runtime: "런타임",
    updateId: "업데이트 ID",
    currentSource: "현재 소스",
    lastCheck: "마지막 업데이트 확인",
    neverChecked: "아직 확인하지 않음",
    lastResultNoUpdate: "최신",
    lastResultDownloaded: "다운로드됨",
    lastResultError: "실패",
    embeddedSource: "앱 내장 버전",
    otaSource: "EAS OTA 업데이트",
    check: "업데이트 확인 및 다운로드",
    checking: "확인 중…",
    restartDownloaded: "재시작하여 다운로드한 업데이트 적용",
    statusDisabled: "개발 환경에서는 OTA 업데이트를 확인하지 않습니다.",
    statusThrottled: "방금 업데이트를 확인했습니다.",
    statusNoUpdate: "현재 버전이 최신입니다.",
    statusDownloaded: "업데이트를 다운로드했습니다. 지금 재시작하거나 다음 콜드 스타트에 적용할 수 있습니다.",
    statusError: "업데이트 확인에 실패했습니다. 현재 안정 버전을 계속 사용할 수 있습니다.",
    applyTitle: "새 버전 적용",
    applyMessage: "앱이 즉시 재시작됩니다.",
    applyNow: "지금 재시작",
    operationFailed: "작업에 실패했습니다. 현재 안정 버전은 계속 사용할 수 있습니다.",
    sectionRemote: "원격 구성 및 긴급 스위치",
    configSource: "구성 소스",
    configVersion: "구성 버전",
    maintenanceMode: "점검 모드",
    paymentFeature: "결제 기능",
    enabled: "켜짐",
    disabled: "꺼짐",
    refreshConfig: "원격 구성 새로고침",
    refreshingConfig: "새로고침 중…",
    remoteRefreshFailed: "새로고침에 실패하여 캐시 또는 내장 기본값을 사용합니다.",
    sectionNative: "설치된 네이티브 기능 확인",
    notificationPermission: "알림 권한",
    photoPicker: "사진 보관함 선택",
    currentLocation: "현재 위치",
    allowed: "허용됨",
    notAllowed: "허용 안 됨",
    selectedFiles: "파일 {count}개 선택",
    nativeCheckFailed: "네이티브 기능 확인에 실패했습니다.",
    sectionDiagnostics: "진단",
    app: "앱",
    api: "API",
    copyDiagnostics: "민감 정보 없는 진단 정보 복사",
    copiedTitle: "복사됨",
    copiedMessage: "계정 정보나 토큰 없이 업데이트 진단을 복사했습니다.",
  },
  es: {
    settingsEntry: "Actualizaciones y diagnóstico",
    screenTitle: "Diagnóstico de actualizaciones",
    sectionUpdate: "Actualizaciones OTA",
    environmentChannel: "Entorno / canal",
    runtime: "Runtime",
    updateId: "ID de actualización",
    currentSource: "Origen actual",
    lastCheck: "Última comprobación",
    neverChecked: "Aún no comprobado",
    lastResultNoUpdate: "Actualizado",
    lastResultDownloaded: "Descargada",
    lastResultError: "Falló",
    embeddedSource: "Versión incluida en la app",
    otaSource: "Actualización OTA de EAS",
    check: "Buscar y descargar actualización",
    checking: "Buscando…",
    restartDownloaded: "Reiniciar y aplicar la actualización descargada",
    statusDisabled: "Las actualizaciones OTA están desactivadas en desarrollo.",
    statusThrottled: "La actualización se comprobó hace un momento.",
    statusNoUpdate: "Ya tienes la última versión.",
    statusDownloaded: "La actualización se descargó. Reinicia ahora o aplícala en el próximo inicio en frío.",
    statusError: "No se pudo buscar la actualización. Puedes seguir usando la versión estable actual.",
    applyTitle: "Aplicar nueva versión",
    applyMessage: "La app se reiniciará inmediatamente.",
    applyNow: "Reiniciar ahora",
    operationFailed: "La operación falló. La versión estable actual sigue disponible.",
    sectionRemote: "Configuración remota e interruptores de emergencia",
    configSource: "Origen de configuración",
    configVersion: "Versión de configuración",
    maintenanceMode: "Modo de mantenimiento",
    paymentFeature: "Función de pagos",
    enabled: "Activado",
    disabled: "Desactivado",
    refreshConfig: "Actualizar configuración remota",
    refreshingConfig: "Actualizando…",
    remoteRefreshFailed: "La actualización falló; se mantienen la caché o los valores integrados.",
    sectionNative: "Comprobación de funciones nativas instaladas",
    notificationPermission: "Permiso de notificaciones",
    photoPicker: "Selector de fotos",
    currentLocation: "Ubicación actual",
    allowed: "Permitido",
    notAllowed: "No permitido",
    selectedFiles: "Se seleccionaron {count} archivo(s)",
    nativeCheckFailed: "Falló la comprobación de la función nativa.",
    sectionDiagnostics: "Diagnóstico",
    app: "App",
    api: "API",
    copyDiagnostics: "Copiar diagnóstico sin datos sensibles",
    copiedTitle: "Copiado",
    copiedMessage: "Se copió el diagnóstico sin datos de cuenta ni tokens.",
  },
  fr: {
    settingsEntry: "Mises à jour et diagnostic",
    screenTitle: "Diagnostic des mises à jour",
    sectionUpdate: "Mises à jour OTA",
    environmentChannel: "Environnement / canal",
    runtime: "Runtime",
    updateId: "ID de mise à jour",
    currentSource: "Source actuelle",
    lastCheck: "Dernière vérification",
    neverChecked: "Pas encore vérifié",
    lastResultNoUpdate: "À jour",
    lastResultDownloaded: "Téléchargée",
    lastResultError: "Échec",
    embeddedSource: "Version intégrée à l’app",
    otaSource: "Mise à jour OTA EAS",
    check: "Rechercher et télécharger une mise à jour",
    checking: "Recherche…",
    restartDownloaded: "Redémarrer et appliquer la mise à jour téléchargée",
    statusDisabled: "Les mises à jour OTA sont désactivées en développement.",
    statusThrottled: "Une vérification vient d’être effectuée.",
    statusNoUpdate: "Vous utilisez déjà la dernière version.",
    statusDownloaded: "La mise à jour est téléchargée. Redémarrez maintenant ou appliquez-la au prochain démarrage à froid.",
    statusError: "La vérification a échoué. Vous pouvez continuer à utiliser la version stable actuelle.",
    applyTitle: "Appliquer la nouvelle version",
    applyMessage: "L’application va redémarrer immédiatement.",
    applyNow: "Redémarrer",
    operationFailed: "L’opération a échoué. La version stable actuelle reste disponible.",
    sectionRemote: "Configuration distante et interrupteurs d’urgence",
    configSource: "Source de configuration",
    configVersion: "Version de configuration",
    maintenanceMode: "Mode maintenance",
    paymentFeature: "Fonction de paiement",
    enabled: "Activé",
    disabled: "Désactivé",
    refreshConfig: "Actualiser la configuration distante",
    refreshingConfig: "Actualisation…",
    remoteRefreshFailed: "Échec de l’actualisation ; le cache ou les valeurs intégrées restent actifs.",
    sectionNative: "Vérification des fonctions natives installées",
    notificationPermission: "Autorisation des notifications",
    photoPicker: "Sélecteur de photos",
    currentLocation: "Position actuelle",
    allowed: "Autorisé",
    notAllowed: "Non autorisé",
    selectedFiles: "{count} fichier(s) sélectionné(s)",
    nativeCheckFailed: "La vérification de la fonction native a échoué.",
    sectionDiagnostics: "Diagnostic",
    app: "App",
    api: "API",
    copyDiagnostics: "Copier le diagnostic sans données sensibles",
    copiedTitle: "Copié",
    copiedMessage: "Le diagnostic a été copié sans données de compte ni jetons.",
  },
  de: {
    settingsEntry: "Updates und Diagnose",
    screenTitle: "Update-Diagnose",
    sectionUpdate: "OTA-Updates",
    environmentChannel: "Umgebung / Kanal",
    runtime: "Runtime",
    updateId: "Update-ID",
    currentSource: "Aktuelle Quelle",
    lastCheck: "Letzte Update-Prüfung",
    neverChecked: "Noch nicht geprüft",
    lastResultNoUpdate: "Aktuell",
    lastResultDownloaded: "Heruntergeladen",
    lastResultError: "Fehlgeschlagen",
    embeddedSource: "Integrierte App-Version",
    otaSource: "EAS-OTA-Update",
    check: "Update prüfen und herunterladen",
    checking: "Wird geprüft…",
    restartDownloaded: "Neu starten und heruntergeladenes Update anwenden",
    statusDisabled: "OTA-Updates sind in der Entwicklungsumgebung deaktiviert.",
    statusThrottled: "Ein Update wurde gerade geprüft.",
    statusNoUpdate: "Du verwendest bereits die neueste Version.",
    statusDownloaded: "Das Update wurde geladen. Jetzt neu starten oder beim nächsten Kaltstart anwenden.",
    statusError: "Die Update-Prüfung ist fehlgeschlagen. Die aktuelle stabile Version bleibt nutzbar.",
    applyTitle: "Neue Version anwenden",
    applyMessage: "Die App wird sofort neu gestartet.",
    applyNow: "Jetzt neu starten",
    operationFailed: "Der Vorgang ist fehlgeschlagen. Die stabile Version bleibt verfügbar.",
    sectionRemote: "Remote-Konfiguration und Notausschalter",
    configSource: "Konfigurationsquelle",
    configVersion: "Konfigurationsversion",
    maintenanceMode: "Wartungsmodus",
    paymentFeature: "Zahlungsfunktion",
    enabled: "Ein",
    disabled: "Aus",
    refreshConfig: "Remote-Konfiguration aktualisieren",
    refreshingConfig: "Wird aktualisiert…",
    remoteRefreshFailed: "Aktualisierung fehlgeschlagen; Cache oder integrierte Standardwerte bleiben aktiv.",
    sectionNative: "Prüfung installierter nativer Funktionen",
    notificationPermission: "Mitteilungsberechtigung",
    photoPicker: "Fotoauswahl",
    currentLocation: "Aktueller Standort",
    allowed: "Erlaubt",
    notAllowed: "Nicht erlaubt",
    selectedFiles: "{count} Datei(en) ausgewählt",
    nativeCheckFailed: "Die Prüfung der nativen Funktion ist fehlgeschlagen.",
    sectionDiagnostics: "Diagnose",
    app: "App",
    api: "API",
    copyDiagnostics: "Diagnose ohne sensible Daten kopieren",
    copiedTitle: "Kopiert",
    copiedMessage: "Die Update-Diagnose wurde ohne Kontodaten oder Tokens kopiert.",
  },
  "pt-BR": {
    settingsEntry: "Atualizações e diagnóstico",
    screenTitle: "Diagnóstico de atualizações",
    sectionUpdate: "Atualizações OTA",
    environmentChannel: "Ambiente / canal",
    runtime: "Runtime",
    updateId: "ID da atualização",
    currentSource: "Origem atual",
    lastCheck: "Última verificação",
    neverChecked: "Ainda não verificado",
    lastResultNoUpdate: "Atualizado",
    lastResultDownloaded: "Baixada",
    lastResultError: "Falhou",
    embeddedSource: "Versão integrada ao app",
    otaSource: "Atualização OTA do EAS",
    check: "Verificar e baixar atualização",
    checking: "Verificando…",
    restartDownloaded: "Reiniciar e aplicar atualização baixada",
    statusDisabled: "Atualizações OTA estão desativadas no desenvolvimento.",
    statusThrottled: "Uma verificação acabou de ser concluída.",
    statusNoUpdate: "Você já está usando a versão mais recente.",
    statusDownloaded: "A atualização foi baixada. Reinicie agora ou aplique no próximo início a frio.",
    statusError: "Falha ao verificar atualização. Você pode continuar usando a versão estável atual.",
    applyTitle: "Aplicar nova versão",
    applyMessage: "O app será reiniciado imediatamente.",
    applyNow: "Reiniciar agora",
    operationFailed: "A operação falhou. A versão estável atual continua disponível.",
    sectionRemote: "Configuração remota e controles de emergência",
    configSource: "Origem da configuração",
    configVersion: "Versão da configuração",
    maintenanceMode: "Modo de manutenção",
    paymentFeature: "Função de pagamento",
    enabled: "Ativado",
    disabled: "Desativado",
    refreshConfig: "Atualizar configuração remota",
    refreshingConfig: "Atualizando…",
    remoteRefreshFailed: "Falha ao atualizar; o cache ou os padrões integrados continuam ativos.",
    sectionNative: "Verificação de recursos nativos instalados",
    notificationPermission: "Permissão de notificações",
    photoPicker: "Seletor de fotos",
    currentLocation: "Localização atual",
    allowed: "Permitido",
    notAllowed: "Não permitido",
    selectedFiles: "{count} arquivo(s) selecionado(s)",
    nativeCheckFailed: "Falha na verificação do recurso nativo.",
    sectionDiagnostics: "Diagnóstico",
    app: "App",
    api: "API",
    copyDiagnostics: "Copiar diagnóstico sem dados sensíveis",
    copiedTitle: "Copiado",
    copiedMessage: "O diagnóstico foi copiado sem dados de conta ou tokens.",
  },
  ru: {
    settingsEntry: "Обновления и диагностика",
    screenTitle: "Диагностика обновлений",
    sectionUpdate: "OTA-обновления",
    environmentChannel: "Среда / канал",
    runtime: "Runtime",
    updateId: "ID обновления",
    currentSource: "Текущий источник",
    lastCheck: "Последняя проверка",
    neverChecked: "Ещё не проверялось",
    lastResultNoUpdate: "Актуально",
    lastResultDownloaded: "Загружено",
    lastResultError: "Ошибка",
    embeddedSource: "Встроенная версия приложения",
    otaSource: "OTA-обновление EAS",
    check: "Проверить и скачать обновление",
    checking: "Проверка…",
    restartDownloaded: "Перезапустить и применить скачанное обновление",
    statusDisabled: "OTA-обновления отключены в среде разработки.",
    statusThrottled: "Обновления только что были проверены.",
    statusNoUpdate: "У вас уже установлена последняя версия.",
    statusDownloaded: "Обновление загружено. Перезапустите сейчас или примените при следующем холодном запуске.",
    statusError: "Не удалось проверить обновление. Можно продолжить работу на текущей стабильной версии.",
    applyTitle: "Применить новую версию",
    applyMessage: "Приложение немедленно перезапустится.",
    applyNow: "Перезапустить",
    operationFailed: "Операция не выполнена. Текущая стабильная версия остаётся доступной.",
    sectionRemote: "Удалённая конфигурация и аварийные переключатели",
    configSource: "Источник конфигурации",
    configVersion: "Версия конфигурации",
    maintenanceMode: "Режим обслуживания",
    paymentFeature: "Платежи",
    enabled: "Вкл.",
    disabled: "Выкл.",
    refreshConfig: "Обновить удалённую конфигурацию",
    refreshingConfig: "Обновление…",
    remoteRefreshFailed: "Обновление не удалось; используется кэш или встроенные значения.",
    sectionNative: "Проверка установленных нативных возможностей",
    notificationPermission: "Разрешение на уведомления",
    photoPicker: "Выбор фото",
    currentLocation: "Текущее местоположение",
    allowed: "Разрешено",
    notAllowed: "Не разрешено",
    selectedFiles: "Выбрано файлов: {count}",
    nativeCheckFailed: "Не удалось проверить нативную возможность.",
    sectionDiagnostics: "Диагностика",
    app: "Приложение",
    api: "API",
    copyDiagnostics: "Копировать диагностику без конфиденциальных данных",
    copiedTitle: "Скопировано",
    copiedMessage: "Диагностика скопирована без данных аккаунта и токенов.",
  },
  "zh-Hans": {
    settingsEntry: "更新与诊断",
    screenTitle: "更新诊断",
    sectionUpdate: "热更新",
    environmentChannel: "环境 / Channel",
    runtime: "Runtime",
    updateId: "Update ID",
    currentSource: "当前来源",
    lastCheck: "最近检查更新",
    neverChecked: "尚未检查",
    lastResultNoUpdate: "已是最新",
    lastResultDownloaded: "已下载",
    lastResultError: "失败",
    embeddedSource: "安装包内置版本",
    otaSource: "EAS OTA 更新",
    check: "检查并下载更新",
    checking: "正在检查…",
    restartDownloaded: "重启并应用已下载更新",
    statusDisabled: "开发环境不会检查 OTA 更新。",
    statusThrottled: "刚刚检查过更新。",
    statusNoUpdate: "当前已经是最新版本。",
    statusDownloaded: "更新已下载。现在可重启应用，或下次冷启动自动生效。",
    statusError: "检查更新失败，不影响继续使用当前稳定版本。",
    applyTitle: "应用新版本",
    applyMessage: "应用会立即重启。",
    applyNow: "立即重启",
    operationFailed: "操作失败，当前稳定版本仍可继续使用。",
    sectionRemote: "远程配置与紧急开关",
    configSource: "配置来源",
    configVersion: "配置版本",
    maintenanceMode: "维护模式",
    paymentFeature: "支付功能",
    enabled: "开启",
    disabled: "关闭",
    refreshConfig: "刷新远程配置",
    refreshingConfig: "正在刷新…",
    remoteRefreshFailed: "刷新失败，已继续使用缓存或内置默认值。",
    sectionNative: "预装原生能力自检",
    notificationPermission: "通知权限",
    photoPicker: "相册选择",
    currentLocation: "当前位置",
    allowed: "已允许",
    notAllowed: "未允许",
    selectedFiles: "选择了 {count} 个文件",
    nativeCheckFailed: "原生能力检查失败。",
    sectionDiagnostics: "诊断",
    app: "App",
    api: "API",
    copyDiagnostics: "复制无敏感信息的诊断数据",
    copiedTitle: "已复制",
    copiedMessage: "更新诊断信息已复制，不包含账号或 Token。",
  },
  "zh-Hant": {
    settingsEntry: "更新與診斷",
    screenTitle: "更新診斷",
    sectionUpdate: "熱更新",
    environmentChannel: "環境 / Channel",
    runtime: "Runtime",
    updateId: "Update ID",
    currentSource: "目前來源",
    lastCheck: "最近檢查更新",
    neverChecked: "尚未檢查",
    lastResultNoUpdate: "已是最新",
    lastResultDownloaded: "已下載",
    lastResultError: "失敗",
    embeddedSource: "安裝包內建版本",
    otaSource: "EAS OTA 更新",
    check: "檢查並下載更新",
    checking: "正在檢查…",
    restartDownloaded: "重新啟動並套用已下載更新",
    statusDisabled: "開發環境不會檢查 OTA 更新。",
    statusThrottled: "剛剛檢查過更新。",
    statusNoUpdate: "目前已是最新版本。",
    statusDownloaded: "更新已下載。現在可重新啟動，或於下次冷啟動時生效。",
    statusError: "檢查更新失敗，不影響繼續使用目前穩定版本。",
    applyTitle: "套用新版本",
    applyMessage: "App 會立即重新啟動。",
    applyNow: "立即重新啟動",
    operationFailed: "操作失敗，目前穩定版本仍可繼續使用。",
    sectionRemote: "遠端設定與緊急開關",
    configSource: "設定來源",
    configVersion: "設定版本",
    maintenanceMode: "維護模式",
    paymentFeature: "付款功能",
    enabled: "開啟",
    disabled: "關閉",
    refreshConfig: "重新整理遠端設定",
    refreshingConfig: "正在重新整理…",
    remoteRefreshFailed: "重新整理失敗，已繼續使用快取或內建預設值。",
    sectionNative: "預裝原生能力自我檢查",
    notificationPermission: "通知權限",
    photoPicker: "相簿選擇",
    currentLocation: "目前位置",
    allowed: "已允許",
    notAllowed: "未允許",
    selectedFiles: "已選擇 {count} 個檔案",
    nativeCheckFailed: "原生能力檢查失敗。",
    sectionDiagnostics: "診斷",
    app: "App",
    api: "API",
    copyDiagnostics: "複製不含敏感資訊的診斷資料",
    copiedTitle: "已複製",
    copiedMessage: "更新診斷資訊已複製，不包含帳號或 Token。",
  },
};

export function updateCopy(language: CatalogLanguage): UpdateCopy {
  return copies[language] ?? en;
}

export function formatUpdateCopy(value: string, replacements: Record<string, string | number>): string {
  return Object.entries(replacements).reduce(
    (result, [key, replacement]) => result.replaceAll(`{${key}}`, String(replacement)),
    value,
  );
}
